### ISSUE TITLE
init command error

### ISSUE THREAD

**Issue by prasadtalasila** [SebastinSanty/autograder-cli#1]
After installation, I tried the `autograder init` command. The following error came up.
```
/usr/lib/node_modules/autolab-cli/index.js:53
	if (prefs.gitlab.time - Math.floor(Date.now() / 1000) < 7200) {
	                ^

TypeError: Cannot read property 'time' of undefined
    at init (/usr/lib/node_modules/autolab-cli/index.js:53:18)
    at Object.<anonymous> (/usr/lib/node_modules/autolab-cli/index.js:183:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

```

**Comment by SebastinSanty** [comment]
Solved the issue [c73faeb](https://github.com/SebastinSanty/autograder-cli/commit/c73faeb7cd6e64fdddef07f29e7b178e1e723f50). Was coming due to prefs not being checked initially.
